### ISSUE TITLE
Torchinterp1d is not optional

### ISSUE THREAD

**Issue by SterlingYM** [pmelchior/spender#53]
This is a very minor comment (sorry), but it would be nice to clarify that torchinterp1d is needed to run minimal example in the README. It is written in the ```Installation (optional: for development)``` section, but it looks like torchinterp1d is *not* optional. Thanks!

**Comment by SterlingYM** [comment]
Also I had to install ```humanize``` and ```GPUtil``` as additional dependencies.

**Comment by pmelchior** [comment]
I assume that you have not installed `spender` from source or from `pip`. Can you confirm?

In these cases, we have no way of ensuring that all dependencies are present, but we should let users know.

**Comment by SterlingYM** [comment]
Yes, it was before doing ```pip install spender```, and I can confirm ```spender``` itself has correct dependencies on the latest PyPI version. 

I understand there's no way of providing full set of dependencies without spender install. Do you think a dummy PyPI package (something like ```spender-minimal```) with all necessary dependencies to run the example on README, including forked ```torchinterp1d```,  would help? Their license seems to be ok with this (please double-check).

Again this is a very minor issue, and just updating the README to clarify that some dependencies, most importantly ```torchinterp1d```, would be sufficient.

**Comment by pmelchior** [comment]
I think the easiest way is to add the instruction to the install instructions. `spender-minimal` doesn't make sense to me because it's just as complicated as a `spender` install. But maybe the `hub` mechanism is only reasonable when there are no package dependencies. Will need to investigate.
